### ISSUE TITLE
Remove Beholder/Mechamarkers code from PhET sims.

### ISSUE THREAD

**Issue by zepumph** [phetsims/tangible#11]
@emily-phet @BLFiedler @terracoda any objections here? It seems like MediaPipe and openCV is the way forward for our computer vision needs.

**Comment by emily-phet** [comment]
No objections from me.

**Comment by brettfiedler** [comment]
No objections here.

**Comment by terracoda** [comment]
No objections from me either.

**Comment by zepumph** [comment]
All has been removed. This means:

* beholder-detection script from sherpa
* Usages in RAP
* Usages in Quad
* Tangible demo
* mechamarkers branch in GFL
* Update the README for Tangible to talk a bit about MediaPipe


@jessegreenberg I removed some stuff from Quad, but had one question. Do we still need `markerRotationProperty` and `rotationMarkerDetectedProperty`? It seems like they were only used with beholder marker input, but I wanted to be sure, in case "marker" was an overloaded name. I marked TODOs to this issue where ever I saw reference to marker input.

**Comment by jessegreenberg** [comment]
I don't see any changes to quadrilateral and that repo is still using tangible code, did the commit to quadrilateral not go through?

**Comment by jessegreenberg** [comment]
Thanks, was done above back to me to look at TODOs.

**Comment by jessegreenberg** [comment]
Yes indeed, "marker" was an overloaded term here and was being used in some hacky OpenCV prototypes. I renamed some Properties in quad to refer more generally to "tangible" and removed the TODOs pointing to this issue.

I don't see any "beholder" or "mechamarkers" references in the project so I assume this can be closed now.
